### PR TITLE
Fully working version with docs

### PR DESCRIPTION
**Pull request by macros**
Better working version, ready to upstream I think

### CODE REVIEW

**Comment by directionless** [comment]
I feel a little weird about the stacked merges. I'm not sure if that's a common ruby idiom, though it seems like there should be a cleaner way. 

Either via pushing a bunch through a single anonymous hash. Or something like

```
hashes = [
  {a: 1},
  {a: 'a', b: 2},
  {c: 3},
]

hashes.reduce(:merge)
```

**Comment by macros** [comment]
I reverted that part to match upstream and just operate on the compiler_flags.

**Comment by macros** [comment]
To your question, I don't know why upstream choose that approach instead of an ordered list.

**Comment by directionless** [comment]
Ah, if that's what upstream does than I got nothing. ¯_(ツ)_/¯
Seems fine.
Approved

**Pull request merged**
